apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-configuration
  name: test-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-constraints
  template:
    metadata:
      labels:
        app: test-constraints
    spec:
      imagePullSecrets:
      - name: pull-secret-principles
      automountServiceAccountToken: false
      containers:
      - image: harbor.long-running.dev-ck8s.com/nginx-unprivileged/nginx-unprivileged:mainline-perl
        name: nginx
        env:                               # Miljövariabler för programmet kan komma från 
        - name: MAX_THREADS                # ConfigMaps eller från Secrets (eller anges direkt).
          valueFrom:                       # Här kommer rätt värde från en ConfigMap,
            configMapKeyRef:               # som refereras till med
              name: configuration-values   # namnet på ConfigMap:en som sådan och
              key: threads                 # själva nyckeln i den ConfigMap:en
        
        volumeMounts:                      # Vi kan också läsa in ConfigMaps och Secrets helt som
        - name: credentials                # filsystem -- här beskriver vi vilket namnet (internt för denna spec, måste matcha det på rad 52)
          mountPath: "/etc/credentials"    # är och var den skall monteras in, som under /etc/credentials
          readOnly: true                   # Det är bra praxis att montera med read-only, för skrivningar kommer inte propageras

        resources:
          requests:
            cpu: 50m
            memory: 128M
          limits:
            cpu: 100m
            memory: 128M
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile: 
            type: "RuntimeDefault"
          capabilities:
            drop:
              - "ALL"

      volumes:                             # Här definierar vi en lista av "volumes", som vi kan referera till inuti denna spec.
      - name: credentials                  # Vi kallar en för "credentials" och fyller den med innehållet från
        secret:                            # den Secret som heter sensitive-values
          secretName: sensitive-values