apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-constraints
  name: test-constraints
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-constraints
  template:
    metadata:
      labels:
        app: test-constraints
    spec:
      imagePullSecrets:
      - name: pull-secret-principles
      automountServiceAccountToken: false
      containers:
      - image: harbor.long-running.dev-ck8s.com/nginx-unprivileged/nginx-unprivileged:mainline-perl
        name: nginx
        resources:
          requests:
            cpu: 50m
            memory: 128M
          limits:
            cpu: 100m
            memory: 128M
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile: 
            type: "RuntimeDefault"
          capabilities:
            drop:
              - "ALL"