apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-hpa
  name: test-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-hpa
  template:
    metadata:
      labels:
        app: test-hpa
    spec:
      topologySpreadConstraints:
      - topologyKey: kubernetes.io/hostname
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: test-hpa
      imagePullSecrets:
      - name: pull-secret-principles
      automountServiceAccountToken: false
      containers:
      - image: harbor.long-running.dev-ck8s.com/nginx-unprivileged/nginx-unprivileged:mainline-perl
        name: nginx
        resources:
          requests:
            cpu: 50m
            memory: 128M
          limits:
            cpu: 100m
            memory: 128M
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile: 
            type: "RuntimeDefault"
          capabilities:
            drop:
              - "ALL"
